image: maven:3.6.3

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn -B verify --file pom.xml
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights
              - pipe: atlassian/checkstyle-report:0.3.0
        - step:
            name: Security Scan
            script:
              # Security scan for sensitive data
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
            name: SonarCloud Scan
            script:
              # Detect bugs & vulnerabilities
              - pipe: sonarsource/sonarcloud-scan:1.4.0
